### ISSUE TITLE
Post-Create no longer working??

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_westvault#11]
For reasons unknown, islandora_westvault_islandora_bagit_post_create() is no longer getting triggered.

[The code hasn't changed](https://github.com/bondjimbond/islandora_westvault/blob/7.x/includes/utilities.inc#L38-L48)... 

But my bags are no longer moving, and the watchdog messages aren't even getting triggered.

This is weird.

**Comment by mjordan** [comment]
I'll take a look this evening.

**Comment by bondjimbond** [comment]
Looks like a problem with my local vagrant environment, not the module.
