### ISSUE TITLE
Flat out not working in production environment

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_westvault#14]
While Islandora Westvault is working beautifully in a fresh Vagrant environment, I cannot get it working in my production site.

If the module is enabled, the config link does not show up, it doesn't appear in the menu, and the Preservation tab does not appear when managing objects.

Why? No idea. Other newly-installed modules work fine.

@mjordan Do you notice anything unusual in how I've written the code that might somehow be incompatible with a different PHP version or OS?

**Comment by mjordan** [comment]
Anything in your apache error logs?

**Comment by bondjimbond** [comment]
No errors I can find. (In /var/log/httpd/error_log)

I'm not sure if there are other places to look for such errors.

**Comment by mjordan** [comment]
You don't have the https://github.com/mjordan/islandora_westvault module installed by any chance?

**Comment by bondjimbond** [comment]
Haha... no, it's the right module.

**Comment by bondjimbond** [comment]
Should also mention that all modules are up to date.

**Comment by bondjimbond** [comment]
Fixed with latest commit! For some reason the permission settings work working OK in the vagrant environment, but not in the production environment, despite no difference in code.

Got permissions set up properly, and we're good!
