### ISSUE TITLE
How to handle Compound Objects

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_westvault#26]
What happens when you Bag a compound object? Do its children get bundled in?

If so -- no problem, we're good to go. If not -- something to figure out.

**Comment by mjordan** [comment]
See https://github.com/bondjimbond/islandora_westvault/issues/25#issuecomment-475637149.

**Comment by bondjimbond** [comment]
Depending on how things go with development on Islandora Bagit -- if we aren't expecting changes anytime soon for compound objects, my approach would be to test the content model when the preservation box is checked, and automatically apply the PRESERVATION datastream to all compound children.

**Comment by bondjimbond** [comment]
Addressed with #36
