### ISSUE TITLE
Move bagit function to drush

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_westvault#30]
Started a branch for this: https://github.com/bondjimbond/islandora_westvault/tree/move_to_drush

But it's no good -- nothing works.

In part there's a permission issue -- mkdir doesn't work, files aren't moved, etc. And then the confirmPreserved tag isn't applied to the PRESERVATION datastream.

Needs a lot of work to make it work. Or is it fine to just leave it in Drupal cron? (Suppose the only way to know for sure is to create a lot of objects, tag them for preservation, and let it happen.)

**Comment by mjordan** [comment]
@bondjimbond I am happy to take a look at this and the other open issues next week, when I have some time.

**Comment by bondjimbond** [comment]
Thanks, @mjordan. Please review my Bagit PR when you get a chance as well -- I've fixed an old issue that is pertinent to our needs.

**Comment by mjordan** [comment]
I will do that. I am traveling next week and am taking my hacking laptop with me.......

**Comment by bondjimbond** [comment]
Confirmed that Drupal cron - at least when run from browser - is no good for large bagging jobs. Generated 100 large image objects and gave each a PRESERVATION datastream. Ran cron -- "cron ran successfully" but no bags generated.

**Comment by mjordan** [comment]
@bondjimbond, this works (I think):

```
sudo drush -u 1 run-islandora-westvault-bagit
Bag created and saved at sites/default/files/Bag-islandora_28.tgz                                                               [status]
Files added: RELS-EXT.rdf, MODS.xml, DC.xml, OBJ.jpg, TECHMD.xml, TN.jpg, MEDIUM_SIZE.jpg, PRESERVATION.bin                     [status]
Bag created and saved at sites/default/files/Bag-islandora_25.tgz                                                               [status]
Files added: RELS-EXT.rdf, MODS.xml, DC.xml, OBJ.jpg, TECHMD.xml, TN.jpg, MEDIUM_SIZE.jpg, PRESERVATION.bin                     [status]
vagrant@islandora:/var/www/drupal/sites/all/modules/islandora_westvault$ ls /tmp/owncloud/
Bag-islandora_25.tgz  Bag-islandora_28.tgz
```

I ran it using `sudo` to overcome the permission issue you identified. That issue exists because the Bagit temp dir is owned by the web server user, which isn't the user who is running drush.

**Comment by bondjimbond** [comment]
Thanks for reviewing. Did you try putting it in cron? If crontab is edited as root (`sudo crontab -e`), I'm thinking it wouldn't need the `sudo` piece in the command - but I'm not certain.

**Comment by bondjimbond** [comment]
Just tried `sudo drush -u 1 westvault-bagit`. Bags created, but they were stuck in sites/default/files -- the post_create function (in includes/utilities.inc) doesn't seem to get called. Does this need to be in the drush script instead?

**Comment by bondjimbond** [comment]
Never mind, it does work. So this is good to go.

**Comment by mjordan** [comment]
There is a typo (weestvault) in https://github.com/bondjimbond/islandora_westvault/blob/move_to_drush/islandora_westvault.drush.inc#L25.

**Comment by bondjimbond** [comment]
No worries, that was fixed before I merged it.
