### ISSUE TITLE
Ignore Solr limit

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_westvault#35]
If you've got enough objects with a PRESERVATION datastream, Islandora Westvault eventually fails to catch any new ones.

Why? Because it uses Solr, and Solr caps out at whatever limit you set under "Results per page" at admin/islandora/search/islandora_solr/settings.

How can we skip this limit?

**Comment by bondjimbond** [comment]
@mjordan I feel like this is a simple fix that I just don't know the answer to.

**Comment by mjordan** [comment]
Set the limit in https://github.com/bondjimbond/islandora_westvault/blob/7.x/includes/utilities.inc#L6 to 1000000 or some other very high number.

**Comment by bondjimbond** [comment]
Any suggestions for exactly how to do this? I'm trying a bunch of ways to set the number of rows, but I'm not succeeding:

```
function islandora_westvault_get_preservation_targets() {
  // Looking for the PRESERVATION datastream
  $query = "fedora_datastreams_ms:PRESERVATION";
  $qp = new islandoraSolrQueryProcessor();
  $qp->buildQuery($query);
  $qp->solrParams['fl'] = "PID";
  $qp->solrParams['rows'] = "1000000";
  $qp->executeQuery(FALSE);
  try {
    $results = $qp->islandoraSolrResult['response']['objects'];
  }
  catch (Exception $e) {
    watchdog_exception('Islandora Westvault', $e, 'Got an exception searching for PRESERVATION datastreams.', array(), WATCHDOG_ERROR);
    $results = array();
  }
  $objects = array();
  if ($results) {
    foreach ($results AS $result) {
      $objects[] = $result['PID'];
    }
  }
  return $objects;
}
```

**Comment by mjordan** [comment]
Try $query_processor->solrLimit = '1000000';

**Comment by bondjimbond** [comment]
That was... weird. Didn't work, and I don't know what it actually did:

> Creating default object from empty value utilities.inc:12

**Comment by bondjimbond** [comment]
Got it thanks to Jordan in the Google group:

` $qp->solrLimit = 1000000;`
