### ISSUE TITLE
Handling the 2 GB size limit

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_westvault#45]
For now, we know that Westvault cannot handle Bags greater than 2 GB in size.

For near-future development, we will need to write some updates to handle this.

This could be done in one of several ways:
1. Alongside the code written for #22 - create the Bag, check out its filesize, and reject if it's too big. Upside: 100% certain of the size and whether or not the Bag is acceptable. Downside: wasted time making the bag.
2. Analyze the object first: find the size of the various datastreams, add them up, and see how big they are. Upside: don't waste time creating a Bag. Downside: This sounds very hard to write, plus you can't really predict how big a zipped Bag will be vs. the sum of its parts. Maybe best to just go ahead and create the Bag instead.
3. ???

@mjordan Any other ideas?

**Comment by mjordan** [comment]
I like number 1. It's the size of the Bag file that matters, not the size of the datastream.

**Comment by bondjimbond** [comment]
Handled with #46.
