### ISSUE TITLE
Use traversal method from islandora_xacml_editor

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_westvault#9]
Trying now to copy the [traversal settings from islandora_xacml_editor](https://github.com/Islandora/islandora_xacml_editor/blob/eb6e45aeb241aab847672373abcb31048ae4e70e/includes/form.inc#L202-L247) in the [management form](https://github.com/bondjimbond/islandora_westvault/blob/traversal/includes/management_form.inc#L40-L90).

First goal is to actually get the options to appear on the form. So far not much success.

**Comment by bondjimbond** [comment]
@mjordan Did you see the invitation link by the way? You still aren't a collaborator.

**Comment by mjordan** [comment]
The form is showing up for me, in the traversal branch:

![westvault_children](https://user-images.githubusercontent.com/403918/54170972-05ef4380-4436-11e9-8fd1-f0d3f254fda4.png)

**Comment by bondjimbond** [comment]
@mjordan The comment at the start of this issue is somewhat outdated. :) 

Right now we have very basic child object preservation on collections: https://github.com/bondjimbond/islandora_westvault/blob/traversal/includes/management_form.inc#L77-L85

Next steps required:
- In that foreach loop on line 81, cherck if a PRESERVATION datastream already exists on the child object
- Find a way to hook into the ingest steps - if new object is child of collection with these settings, apply the PRESERVATION datastream

**Comment by bondjimbond** [comment]
I'm thinking about my strategy for dealing with collections. Here's my idea...

1. When a collection is preserved, collection gets a PRESERVATION datastream. So do all its current children, if they haven't already got one. (Done.)
2. Using [hook_islandora_object_ingested()](https://github.com/Islandora/islandora/blob/7.x/islandora.api.php#L246-L248): when a new object is ingested, check its parent collection. IF parent has a PRESERVATION datastream, create a PRESERVATION datastream (run function [islandora_westvault_add_preservation_datastream()](https://github.com/bondjimbond/islandora_westvault/blob/7.x/includes/management_form.inc#L80)).

Once the above is working, tweak somewhat:
1. When [preserving an object](https://github.com/bondjimbond/islandora_westvault/blob/7.x/includes/management_form.inc#L59), IF it's a collection, check type of preservation (new children only, current children only, old and new children).
2. Add a line into the PRESERVATION datastream: `<collectionPreservationMethod>(SELECTED STRATEGY)</collectionPreservationMethod>`
3. Check preservation method before [sending children through the preservation process](https://github.com/bondjimbond/islandora_westvault/blob/7.x/includes/management_form.inc#L67)
 4. When new objects are ingested, check parent for PRESERVATION datastream. IF datastream exists, read the preservation method and proceed accordingly.

Does that all make sense to you, @mjordan?

**Comment by bondjimbond** [comment]
Addressed with #20 - ignored islandora_xacml_editor and created my own approach.
